package com.google.android.gms.games.internal.player;

import android.text.TextUtils;
import com.google.android.gms.games.internal.zze;

/* compiled from: com.google.android.gms:play-services-games@@19.0.0 */
public final class zzd {
    public final String name;
    public final String zzca;
    public final String zzcf;
    public final String zzmi;
    public final String zzmj;
    public final String zzmk;
    public final String zzml;
    public final String zzmm;
    public final String zzmn;
    public final String zzmo;
    public final String zzmp;
    public final String zzmq;
    public final String zzmr;
    public final String zzms;
    public final String zzmt;
    public final String zzmu;
    public final String zzmv;
    public final String zzmw;
    public final String zzmx;
    private final String zzmy;
    public final String zzmz;
    public final String zzna;
    public final String zznb;
    public final String zznc;
    public final String zznd;
    public final String zzne;
    public final String zznf;
    public final String zzng;
    public final String zznh;
    public final String zzni;
    public final String zznj;
    public final String zznk;
    public final String zznl;
    public final String zznm;
    public final String zznn;
    public final String zzno;
    public final String zznp;
    public final String zznq;
    public final String zznr;

    public zzd(String str) {
        String str2;
        String str3 = "most_recent_game_name";
        String str4 = "most_recent_external_game_id";
        String str5 = "is_profile_visible";
        String str6 = "has_all_public_acls";
        String str7 = "player_title";
        String str8 = "last_level_up_timestamp";
        String str9 = "next_level_max_xp";
        if (TextUtils.isEmpty((CharSequence) null)) {
            this.zzmi = "external_player_id";
            this.zzmj = "profile_name";
            this.zzmk = "profile_icon_image_uri";
            this.zzml = "profile_icon_image_url";
            this.zzmm = "profile_hi_res_image_uri";
            this.zzmn = "profile_hi_res_image_url";
            this.zzmo = "last_updated";
            this.zzmp = "is_in_circles";
            this.zzmq = "played_with_timestamp";
            this.zzmr = "current_xp_total";
            this.zzms = "current_level";
            this.zzmt = "current_level_min_xp";
            this.zzmu = "current_level_max_xp";
            this.zzmv = "next_level";
            this.zzmw = str9;
            this.zzmx = str8;
            this.zzca = str7;
            this.zzmy = str6;
            this.zzmz = str5;
            this.zzna = str4;
            this.zznb = str3;
            this.zznc = "most_recent_activity_timestamp";
            this.zznd = "most_recent_game_icon_uri";
            this.zzne = "most_recent_game_hi_res_uri";
            this.zznf = "most_recent_game_featured_uri";
            this.zzng = "has_debug_access";
            this.zzcf = "gamer_tag";
            this.name = "real_name";
            this.zznh = "banner_image_landscape_uri";
            this.zzni = "banner_image_landscape_url";
            this.zznj = "banner_image_portrait_uri";
            this.zznk = "banner_image_portrait_url";
            this.zznl = "gamer_friend_status";
            this.zznm = "gamer_friend_update_timestamp";
            this.zznn = "is_muted";
            this.zzno = "total_unlocked_achievements";
            this.zznp = zze.zzgq;
            this.zznq = zze.zzgr;
            str2 = zze.zzgs;
        } else {
            String str10 = str9;
            this.zzmi = "external_player_id".length() != 0 ? "null".concat("external_player_id") : new String("null");
            this.zzmj = "profile_name".length() != 0 ? "null".concat("profile_name") : new String("null");
            this.zzmk = "profile_icon_image_uri".length() != 0 ? "null".concat("profile_icon_image_uri") : new String("null");
            this.zzml = "profile_icon_image_url".length() != 0 ? "null".concat("profile_icon_image_url") : new String("null");
            this.zzmm = "profile_hi_res_image_uri".length() != 0 ? "null".concat("profile_hi_res_image_uri") : new String("null");
            this.zzmn = "profile_hi_res_image_url".length() != 0 ? "null".concat("profile_hi_res_image_url") : new String("null");
            this.zzmo = "last_updated".length() != 0 ? "null".concat("last_updated") : new String("null");
            this.zzmp = "is_in_circles".length() != 0 ? "null".concat("is_in_circles") : new String("null");
            this.zzmq = "played_with_timestamp".length() != 0 ? "null".concat("played_with_timestamp") : new String("null");
            this.zzmr = "current_xp_total".length() != 0 ? "null".concat("current_xp_total") : new String("null");
            this.zzms = "current_level".length() != 0 ? "null".concat("current_level") : new String("null");
            this.zzmt = "current_level_min_xp".length() != 0 ? "null".concat("current_level_min_xp") : new String("null");
            this.zzmu = "current_level_max_xp".length() != 0 ? "null".concat("current_level_max_xp") : new String("null");
            this.zzmv = "next_level".length() != 0 ? "null".concat("next_level") : new String("null");
            this.zzmw = str10.length() != 0 ? "null".concat(str10) : new String("null");
            this.zzmx = str8.length() != 0 ? "null".concat(str8) : new String("null");
            this.zzca = str7.length() != 0 ? "null".concat(str7) : new String("null");
            this.zzmy = str6.length() != 0 ? "null".concat(str6) : new String("null");
            this.zzmz = str5.length() != 0 ? "null".concat(str5) : new String("null");
            this.zzna = str4.length() != 0 ? "null".concat(str4) : new String("null");
            this.zznb = str3.length() != 0 ? "null".concat(str3) : new String("null");
            this.zznc = "most_recent_activity_timestamp".length() != 0 ? "null".concat("most_recent_activity_timestamp") : new String("null");
            this.zznd = "most_recent_game_icon_uri".length() != 0 ? "null".concat("most_recent_game_icon_uri") : new String("null");
            this.zzne = "most_recent_game_hi_res_uri".length() != 0 ? "null".concat("most_recent_game_hi_res_uri") : new String("null");
            this.zznf = "most_recent_game_featured_uri".length() != 0 ? "null".concat("most_recent_game_featured_uri") : new String("null");
            this.zzng = "has_debug_access".length() != 0 ? "null".concat("has_debug_access") : new String("null");
            this.zzcf = "gamer_tag".length() != 0 ? "null".concat("gamer_tag") : new String("null");
            this.name = "real_name".length() != 0 ? "null".concat("real_name") : new String("null");
            this.zznh = "banner_image_landscape_uri".length() != 0 ? "null".concat("banner_image_landscape_uri") : new String("null");
            this.zzni = "banner_image_landscape_url".length() != 0 ? "null".concat("banner_image_landscape_url") : new String("null");
            this.zznj = "banner_image_portrait_uri".length() != 0 ? "null".concat("banner_image_portrait_uri") : new String("null");
            this.zznk = "banner_image_portrait_url".length() != 0 ? "null".concat("banner_image_portrait_url") : new String("null");
            this.zznl = "gamer_friend_status".length() != 0 ? "null".concat("gamer_friend_status") : new String("null");
            this.zznm = "gamer_friend_update_timestamp".length() != 0 ? "null".concat("gamer_friend_update_timestamp") : new String("null");
            this.zznn = "is_muted".length() != 0 ? "null".concat("is_muted") : new String("null");
            this.zzno = "total_unlocked_achievements".length() != 0 ? "null".concat("total_unlocked_achievements") : new String("null");
            String valueOf = String.valueOf(zze.zzgq);
            this.zznp = valueOf.length() != 0 ? "null".concat(valueOf) : new String("null");
            String valueOf2 = String.valueOf(zze.zzgr);
            this.zznq = valueOf2.length() != 0 ? "null".concat(valueOf2) : new String("null");
            String valueOf3 = String.valueOf(zze.zzgs);
            str2 = valueOf3.length() != 0 ? "null".concat(valueOf3) : new String("null");
        }
        this.zznr = str2;
    }
}
