package com.google.android.gms.internal.drive;

import com.google.android.gms.common.data.BitmapTeleporter;
import com.google.android.gms.common.util.GmsVersion;
import com.google.android.gms.drive.DriveId;
import com.google.android.gms.drive.metadata.MetadataField;
import com.google.android.gms.drive.metadata.internal.zzb;
import com.google.android.gms.drive.metadata.internal.zzi;
import com.google.android.gms.drive.metadata.internal.zzo;
import com.google.android.gms.drive.metadata.internal.zzs;
import com.google.android.gms.drive.metadata.internal.zzt;
import com.google.android.gms.drive.metadata.internal.zzu;
import java.util.Collections;

public final class zzhs {
    public static final MetadataField<DriveId> zzjl = zzim.zzlj;
    public static final MetadataField<String> zzjm = new zzt("alternateLink", GmsVersion.VERSION_JARLSBERG);
    public static final zzhv zzjn = new zzhv(GmsVersion.VERSION_LONGHORN);
    public static final MetadataField<String> zzjo = new zzt("description", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzjp = new zzt("embedLink", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzjq = new zzt("fileExtension", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Long> zzjr = new zzi("fileSize", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzjs = new zzt("folderColorRgb", GmsVersion.VERSION_QUESO);
    public static final MetadataField<Boolean> zzjt = new zzb("hasThumbnail", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzju = new zzt("indexableText", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Boolean> zzjv = new zzb("isAppData", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Boolean> zzjw = new zzb("isCopyable", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Boolean> zzjx = new zzb("isEditable", GmsVersion.VERSION_HALLOUMI);
    public static final MetadataField<Boolean> zzjy = new zzht("isExplicitlyTrashed", Collections.singleton("trashed"), Collections.emptySet(), GmsVersion.VERSION_ORLA);
    public static final MetadataField<Boolean> zzjz = new zzb("isLocalContentUpToDate", GmsVersion.VERSION_REBLOCHON);
    public static final zzhw zzka = new zzhw("isPinned", GmsVersion.VERSION_HALLOUMI);
    public static final MetadataField<Boolean> zzkb = new zzb("isOpenable", GmsVersion.VERSION_PARMESAN);
    public static final MetadataField<Boolean> zzkc = new zzb("isRestricted", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Boolean> zzkd = new zzb("isShared", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<Boolean> zzke = new zzb("isGooglePhotosFolder", GmsVersion.VERSION_ORLA);
    public static final MetadataField<Boolean> zzkf = new zzb("isGooglePhotosRootFolder", GmsVersion.VERSION_ORLA);
    public static final MetadataField<Boolean> zzkg = new zzb("isTrashable", GmsVersion.VERSION_KENAFA);
    public static final MetadataField<Boolean> zzkh = new zzb("isViewed", GmsVersion.VERSION_JARLSBERG);
    public static final zzhx zzki = new zzhx(GmsVersion.VERSION_HALLOUMI);
    public static final MetadataField<String> zzkj = new zzt("originalFilename", GmsVersion.VERSION_JARLSBERG);
    public static final com.google.android.gms.drive.metadata.zzb<String> zzkk = new zzs("ownerNames", GmsVersion.VERSION_JARLSBERG);
    public static final zzu zzkl = new zzu("lastModifyingUser", GmsVersion.VERSION_MANCHEGO);
    public static final zzu zzkm = new zzu("sharingUser", GmsVersion.VERSION_MANCHEGO);
    public static final zzo zzkn = new zzo(GmsVersion.VERSION_HALLOUMI);
    public static final zzhy zzko = new zzhy("quotaBytesUsed", GmsVersion.VERSION_JARLSBERG);
    public static final zzia zzkp = new zzia("starred", GmsVersion.VERSION_HALLOUMI);
    public static final MetadataField<BitmapTeleporter> zzkq = new zzhu("thumbnail", Collections.emptySet(), Collections.emptySet(), GmsVersion.VERSION_KENAFA);
    public static final zzib zzkr = new zzib("title", GmsVersion.VERSION_HALLOUMI);
    public static final zzic zzks = new zzic("trashed", GmsVersion.VERSION_HALLOUMI);
    public static final MetadataField<String> zzkt = new zzt("webContentLink", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzku = new zzt("webViewLink", GmsVersion.VERSION_JARLSBERG);
    public static final MetadataField<String> zzkv = new zzt("uniqueIdentifier", GmsVersion.VERSION_LONGHORN);
    public static final zzb zzkw = new zzb("writersCanShare", GmsVersion.VERSION_MANCHEGO);
    public static final MetadataField<String> zzkx = new zzt("role", GmsVersion.VERSION_MANCHEGO);
    public static final MetadataField<String> zzky = new zzt("md5Checksum", GmsVersion.VERSION_ORLA);
    public static final zzhz zzkz = new zzhz(GmsVersion.VERSION_ORLA);
    public static final MetadataField<String> zzla = new zzt("recencyReason", GmsVersion.VERSION_SAGA);
    public static final MetadataField<Boolean> zzlb = new zzb("subscribed", GmsVersion.VERSION_SAGA);
}
